require "hoe"

Hoe.plugin :minitest
Hoe.plugin :gemspec
Hoe.plugin :git

Hoe.spec "rulers" do
  developer "Eric Hodel", "drbrain@segment7.net"

  rdoc_locations << "docs.seattlerb.org:/data/www/docs.seattlerb.org/rulers/"

  license "MIT"

  self.readme_file = "README.rdoc"

  dependency "rack",   "~> 2.0"
  dependency "erubis", "~> 2.7"
  dependency "rack-test", "~> 1.1", :development
end

task gem: %w[gem:spec]

# vim: syntax=ruby
