require "hoe"

Hoe.plugin :minitest
Hoe.plugin :git

Hoe.spec "rulers" do
  developer "Eric Hodel", "drbrain@segment7.net"

  rdoc_locations << "docs.seattlerb.org:/data/www/docs.seattlerb.org/rulers/"

  license "MIT"

  self.readme_file = "README.rdoc"

  dependency "rack", "~> 2.0"
end

# vim: syntax=ruby
